
export const FEATURE_CATEGORIES = [
    {
        id: "core_tools",
        label: "Core Tools – Available Now",
        description: "Fast, privacy-friendly tools that work instantly in your browser.",
        features: ["commaSeparator", "compareText", "jsonFormatter", "jsonValidator", "textCleaner", "qrCode", "imageResizer", "imageCompressor"]
    },
    {
        id: "financial_tools",
        label: "Finance & Wealth",
        description: "Professional tools for loans, investments, tax, and wealth planning.",
        features: ["loanPlanner", "sipCalculator", "fixedIncome", "taxPlanner", "retirementPlanner", "investmentPlanner", "inflationCalculator", "netWorthTracker"]
    },
    {
        id: "pdf_tools",
        label: "PDF Tools – Browser Optimized",
        description: "These tools run locally in your browser. Best for small to medium files.",
        features: ["pdfSplit", "pdfMerge", "pdfToJpg", "pdfToPng", "jpgToPdf", "pngToPdf", "pdfPreview", "pdfCompress", "pdfToWebp", "webpToPdf", "pdfToZip", "pdfToText", "pdfToJson", "jsonToPdf", "textToPdf", "csvToPdf", "pdfUnlock", "pdfRotate"]
    },
    {
        id: "pdf_actions",
        label: "PDF Actions – Visual Edits",
        description: "Add signatures, text, dates, and images to your PDF locally.",
        features: ["pdfSign", "pdfAddText", "pdfFillForm", "pdfAddDate", "pdfAddImage", "pdfHighlight"]
    },
    {
        id: "developer_tools",
        label: "Developer Tools",
        description: "Simple, offline-first tools for developers. Encoders, decoders, and converters.",
        features: [
            "baseConverter", "timestampConverter", "dataSizeConverter",
            "base64", "urlEncoder", "htmlEncoder",
            "uuidGenerator", "randomString", "randomNumber",
            "scientificCalc", "percentageCalc", "dateDiff",
            "ipSubnetCalculator", "cidrOverlap",
            "cronGenerator", "chmodCalc",
            "regexTester", "caseConverter", "envConverter",
            "curlConverter", "diffChecker", "cidrSplitter", "k8sConverter",
            "publicIp", "portLookup", "httpStatus",
            "hashGenerator", "cronExplainer", "timezoneConverter",
            "jwtDecoder", "sshGenerator", "sqlRunner"
        ]
    },
    {
        id: "excel_tools",
        label: "Excel & Data Tools",
        description: "Lightweight tools for CSV, Excel, and Data processing. Private & Local.",
        features: [
            "excelToJson", "jsonToExcel", "csvCleaner", "formulaExplainer",
            "excelToCsv", "csvToExcel", "excelToSql", "excelToYaml",
            "excelDataProcessor", "columnSplitter", "transpose",
            "excelDate", "formulaGenerator", "excelErrorExplainer",
            "columnMerger", "headerNormalizer"
        ]
    },
    {
        id: "advanced_tools",
        label: "Advanced Cloud Tools – Under Development",
        description: "These features require heavy cloud processing and are currently being built.",
        features: ["ocr", "pdfToWord", "pdfToExcel", "pdfToCsv", "pdfToHtml", "heavyCompress", "largeFiles", "batchProcessing", "unlimited", "excelToPdf"]
    }
];

export const FEATURES = {
    // CATEGORY 1: CORE TOOLS
    jsonFormatter: {
        title: "JSON Formatter",
        desc: "Format and beautify JSON data.",
        icon: "fa-solid fa-code",
        color: "cyan",
        category: "core_tools",
        mode: "enabled",
        to: "/json-formatter",
        seoTitle: "JSON Formatter",
        seoDesc: "Format and validate JSON instantly in your browser.",
        related: ["jsonValidator", "commaSeparator", "pdfToJson"]
    },
    jsonValidator: {
        title: "JSON Validator",
        desc: "Validate and fix JSON errors.",
        icon: "fa-solid fa-check-double",
        color: "green",
        category: "core_tools",
        mode: "enabled",
        to: "/json-validator",
        seoTitle: "JSON Validator",
        seoDesc: "Check for syntax errors and fix JSON locally.",
        related: ["jsonFormatter", "pdfToJson"]
    },
    commaSeparator: {
        title: "Comma Separator",
        desc: "Convert columns to lists.",
        icon: "fa-solid fa-list",
        color: "blue",
        category: "core_tools",
        mode: "enabled",
        to: "/comma-suparrator",
        seoTitle: "Comma Separator",
        seoDesc: "Convert column data to lists. No server upload.",
        related: ["jsonFormatter", "compareText"]
    },
    compareText: {
        title: "Text Comparison",
        desc: "Analyze differences between texts.",
        icon: "fa-solid fa-code-compare",
        color: "purple",
        category: "core_tools",
        mode: "enabled",
        to: "/compare-text",
        seoTitle: "Text Diff Checker",
        seoDesc: "Compare text blocks side-by-side to find differences.",
        related: ["commaSeparator", "textCleaner"]
    },
    textCleaner: {
        title: "Text Formatter",
        desc: "Clean and format text files.",
        icon: "fa-solid fa-eraser",
        color: "orange",
        category: "core_tools",
        mode: "enabled",
        to: "/text-cleaner",
        seoTitle: "Text Cleaner",
        seoDesc: "Remove formatting and extra spaces instantly.",
        related: ["compareText", "pdfToText"]
    },
    qrCode: {
        title: "QR Code Generator",
        desc: "Create QR codes instantly.",
        icon: "fa-solid fa-qrcode",
        color: "pink",
        category: "core_tools",
        mode: "enabled",
        to: "/qr-code",
        seoTitle: "QR Code Generator",
        seoDesc: "Generate QR codes locally. No tracking.",
        related: ["imageResizer", "imageCompressor"]
    },
    imageResizer: {
        title: "Image Resizer",
        desc: "Resize images to specific dimensions.",
        icon: "fa-solid fa-expand",
        color: "indigo",
        category: "core_tools",
        mode: "enabled",
        to: "/image-resizer",
        seoTitle: "Image Resizer",
        seoDesc: "Resize JPG and PNG images in your browser.",
        related: ["imageCompressor", "pdfToJpg", "jpgToPdf"]
    },
    imageCompressor: {
        title: "Image Compressor",
        desc: "Compress images efficiently.",
        icon: "fa-solid fa-compress",
        color: "teal",
        category: "core_tools",
        mode: "enabled",
        to: "/image-compressor",
        seoTitle: "Image Compressor",
        seoDesc: "Compress images to save space. Best for web use.",
        related: ["imageResizer", "pdfCompress", "pdfToJpg"]
    },
    sqlRunner: {
        title: "SQL Runner",
        desc: "Run SQL on CSV files.",
        icon: "fa-solid fa-database",
        color: "blue",
        category: "developer_tools",
        mode: "enabled",
        to: "/sql-runner",
        seoTitle: "CSV SQL Runner in Browser",
        seoDesc: "Import CSVs and run SQL queries locally.",
        related: ["excelToSql", "csvCleaner"]
    },

    // FINANCIAL & WEALTH TOOLS (REFACTORED)
    loanPlanner: {
        title: "Loan Planner",
        desc: "EMI, Prepayment & Analysis.",
        icon: "fa-solid fa-calculator",
        color: "blue",
        category: "financial_tools",
        mode: "enabled",
        to: "/loan-calculator",
        seoTitle: "Advanced Loan Planner & EMI Calculator",
        seoDesc: "Unified tool for Loan EMI, Prepayment analysis, and Amortization schedules.",
        related: ["taxPlanner", "fixedIncome"]
    },
    sipCalculator: {
        title: "SIP Calculator",
        desc: "Mutual Fund Returns.",
        icon: "fa-solid fa-chart-line",
        color: "purple",
        category: "financial_tools",
        mode: "enabled",
        to: "/sip-calculator",
        seoTitle: "SIP & Mutual Fund Return Calculator",
        seoDesc: "Calculate SIP returns, inflation-adjusted wealth, and step-up SIPs.",
        related: ["investmentPlanner", "fixedIncome"]
    },
    fixedIncome: {
        title: "Fixed Income",
        desc: "FD, RD, PPF Calculator.",
        icon: "fa-solid fa-piggy-bank",
        color: "teal",
        category: "financial_tools",
        mode: "enabled",
        to: "/fixed-income-calculator",
        seoTitle: "Fixed Income Calculator (FD, RD, PPF)",
        seoDesc: "Calculate returns for Fixed Deposits, RDs, and PPF in one place.",
        related: ["taxPlanner", "sipCalculator"]
    },
    taxPlanner: {
        title: "Tax Planner",
        desc: "Old vs New Regime.",
        icon: "fa-solid fa-receipt",
        color: "orange",
        category: "financial_tools",
        mode: "enabled",
        to: "/tax-planner",
        seoTitle: "Income Tax Planner India FY 2024-25",
        seoDesc: "Compare tax regimes and plan deductions (80C, 80D, HRA).",
        related: ["ppfCalculator", "sipCalculator"] // Using ppfCalculator keyword for SEO link though routed to Fixed Income
    },
    retirementPlanner: {
        title: "Retirement Planner",
        desc: "Fire & Corpus Planning.",
        icon: "fa-solid fa-person-cane",
        color: "indigo",
        category: "financial_tools",
        mode: "enabled",
        to: "/retirement-planner",
        seoTitle: "Retirement & FIRE Planner",
        seoDesc: "Plan your retirement corpus with inflation and life expectancy.",
        related: ["sipCalculator", "inflationCalculator"]
    },
    investmentPlanner: {
        title: "Investment Planner",
        desc: "Goal-based Investing.",
        icon: "fa-solid fa-bullseye",
        color: "rose",
        category: "financial_tools",
        mode: "enabled",
        to: "/investment-planner",
        seoTitle: "Goal Based Investment Planner",
        seoDesc: "Plan investments for life goals like House, Education, and Wealth.",
        related: ["sipCalculator", "netWorthTracker"]
    },
    inflationCalculator: {
        title: "Inflation Calc",
        desc: "Future Value of Money.",
        icon: "fa-solid fa-money-bill-trend-up",
        color: "red",
        category: "financial_tools",
        mode: "enabled",
        to: "/inflation-calculator",
        seoTitle: "Inflation Calculator India",
        seoDesc: "Calculate the future value of money and impact of inflation.",
        related: ["retirementPlanner", "fixedIncome"]
    },
    netWorthTracker: {
        title: "Net Worth",
        desc: "Track Assets & Debts.",
        icon: "fa-solid fa-scale-balanced",
        color: "emerald",
        category: "financial_tools",
        mode: "enabled",
        to: "/net-worth-tracker",
        seoTitle: "Personal Net Worth Tracker",
        seoDesc: "Track your assets and liabilities to measure financial health.",
        related: ["investmentPlanner", "loanPlanner"]
    },

    // CATEGORY 2: PDF TOOLS
    pdfSplit: {
        title: "PDF Split",
        desc: "Extract pages from PDFs.",
        icon: "fa-solid fa-scissors",
        color: "orange",
        category: "pdf_tools",
        mode: "limited",
        badge: "Browser Optimized",
        to: "/split-pdf",
        seoTitle: "Split PDF Pages",
        seoDesc: "Split PDF files into pages. Works best with files under 10MB.",
        related: ["pdfMerge", "pdfCompress", "pdfRotate"]
    },
    loanCalculator: {
        title: "Loan / EMI Calculator",
        desc: "Calculate EMI & Prepayments.",
        icon: "fa-solid fa-calculator",
        color: "green",
        category: "financial_tools",
        mode: "enabled",
        to: "/loan-calculator",
        seoTitle: "Advanced Loan EMI Calculator",
        seoDesc: "Calculate Loan EMI, amortization schedule, and prepayment savings.",
        related: ["percentageCalc", "scientificCalc"]
    },
    pdfMerge: {
        title: "PDF Merge",
        desc: "Combine multiple PDFs.",
        icon: "fa-solid fa-object-group",
        color: "red",
        category: "pdf_tools",
        mode: "limited",
        badge: "Browser Optimized",
        to: "/merge-pdf",
        seoTitle: "Merge PDF Files",
        seoDesc: "Combine multiple PDF files locally. Privacy-first merging.",
        related: ["pdfSplit", "pdfCompress", "jpgToPdf"]
    },
    pdfToJpg: {
        title: "PDF → JPG",
        desc: "Convert PDF pages to JPG.",
        icon: "fa-solid fa-image",
        color: "purple",
        category: "pdf_tools",
        mode: "limited",
        badge: "Browser Optimized",
        to: "/pdf-to-jpg",
        seoTitle: "PDF to JPG",
        seoDesc: "Convert PDF pages to JPG images in your browser.",
        related: ["pdfToPng", "jpgToPdf", "imageCompressor"]
    },
    pdfToPng: {
        title: "PDF → PNG",
        desc: "Convert PDF pages to PNG.",
        icon: "fa-solid fa-photo-film",
        color: "indigo",
        category: "pdf_tools",
        mode: "limited",
        badge: "Browser Optimized",
        to: "/pdf-to-png",
        seoTitle: "PDF to PNG",
        seoDesc: "Convert PDF pages to high-quality PNGs.",
        related: ["pdfToJpg", "pngToPdf", "pdfToWebp"]
    },
    jpgToPdf: {
        title: "JPG → PDF",
        desc: "Convert JPG images to PDF.",
        icon: "fa-solid fa-image",
        color: "pink",
        category: "pdf_tools",
        mode: "limited",
        badge: "Browser Optimized",
        to: "/jpg-to-pdf",
        seoTitle: "JPG to PDF",
        seoDesc: "Turn JPG images into a single PDF document locally.",
        related: ["pngToPdf", "pdfToJpg", "pdfMerge"]
    },
    pngToPdf: {
        title: "PNG → PDF",
        desc: "Convert PNG images to PDF.",
        icon: "fa-solid fa-image",
        color: "indigo",
        category: "pdf_tools",
        mode: "limited",
        badge: "Browser Optimized",
        to: "/png-to-pdf",
        seoTitle: "PNG to PDF",
        seoDesc: "Convert PNG images to PDF format instantly.",
        related: ["jpgToPdf", "pdfToPng", "imageResizer"]
    },
    pdfPreview: {
        title: "PDF Viewer",
        desc: "Preview PDF files.",
        icon: "fa-solid fa-eye",
        color: "blue",
        category: "pdf_tools",
        mode: "under_development",
        to: "/pdf-viewer",
        seoTitle: "PDF Viewer",
        seoDesc: "View PDF files directly in your browser.",
        related: ["pdfSplit", "pdfRotate", "pdfCompress"]
    },
    pdfCompress: {
        title: "PDF Compression",
        desc: "Reduce file size.",
        icon: "fa-solid fa-compress",
        color: "green",
        category: "pdf_tools",
        mode: "limited",
        badge: "Browser Optimized",
        to: "/compress-pdf",
        seoTitle: "Compress PDF",
        seoDesc: "Optimize PDF file size. Best for modest size reductions.",
        related: ["heavyCompress", "pdfSplit", "imageCompressor"]
    },
    pdfToWebp: {
        title: "PDF to WebP",
        desc: "Convert PDF to WebP.",
        icon: "fa-brands fa-google",
        color: "orange",
        category: "pdf_tools",
        mode: "limited",
        badge: "Browser Optimized",
        to: "/pdf-to-webp",
        seoTitle: "PDF to WebP",
        seoDesc: "Convert PDF pages to WebP format.",
        related: ["pdfToJpg", "webpToPdf", "pdfToPng"]
    },
    webpToPdf: {
        title: "WebP to PDF",
        desc: "Convert WebP to PDF.",
        icon: "fa-solid fa-image",
        color: "orange",
        category: "pdf_tools",
        mode: "limited",
        badge: "Browser Optimized",
        to: "/webp-to-pdf",
        seoTitle: "WebP to PDF",
        seoDesc: "Turn WebP images into a PDF document.",
        related: ["pdfToWebp", "jpgToPdf", "pngToPdf"]
    },
    pdfToZip: {
        title: "PDF to ZIP",
        desc: "Archive your PDFs.",
        icon: "fa-solid fa-file-zipper",
        color: "pink",
        category: "pdf_tools",
        mode: "limited",
        badge: "Browser Optimized",
        to: "/pdf-to-zip",
        seoTitle: "PDF to ZIP",
        seoDesc: "Bundle PDF files into a ZIP archive.",
        related: ["pdfCompress", "heavyCompress"]
    },
    pdfToText: {
        title: "PDF to Text",
        desc: "Extract text from PDFs.",
        icon: "fa-solid fa-file-lines",
        color: "cyan",
        category: "pdf_tools",
        mode: "limited",
        badge: "Browser Optimized",
        to: "/pdf-to-text",
        seoTitle: "Extract Text from PDF",
        seoDesc: "Get raw text from PDF documents.",
        related: ["pdfToWord", "ocr", "textCleaner"]
    },
    pdfToJson: {
        title: "PDF to JSON",
        desc: "Extract structure to JSON.",
        icon: "fa-solid fa-file-code",
        color: "yellow",
        category: "pdf_tools",
        mode: "limited",
        badge: "Browser Optimized",
        to: "/pdf-to-json",
        seoTitle: "PDF to JSON",
        seoDesc: "Convert PDF content to JSON structure.",
        related: ["jsonFormatter", "pdfToText", "pdfToHtml"]
    },
    jsonToPdf: {
        title: "JSON to PDF",
        desc: "Convert JSON to PDF.",
        icon: "fa-solid fa-code",
        color: "yellow",
        category: "pdf_tools",
        mode: "limited",
        badge: "Browser Optimized",
        to: "/json-to-pdf",
        seoTitle: "JSON to PDF",
        seoDesc: "Convert JSON data into a PDF document.",
        related: ["pdfToJson", "textToPdf", "csvToPdf"]
    },
    textToPdf: {
        title: "Text to PDF",
        desc: "Convert text to PDF.",
        icon: "fa-solid fa-font",
        color: "teal",
        category: "pdf_tools",
        mode: "limited",
        badge: "Browser Optimized",
        to: "/text-to-pdf",
        seoTitle: "Text to PDF",
        seoDesc: "Convert plain text files to PDF.",
        related: ["pdfToText", "pdfToWord", "compareText"]
    },
    csvToPdf: {
        title: "CSV to PDF",
        desc: "Convert CSV to PDF.",
        icon: "fa-solid fa-table",
        color: "green",
        category: "pdf_tools",
        mode: "limited",
        badge: "Browser Optimized",
        to: "/csv-to-pdf",
        seoTitle: "CSV to PDF",
        seoDesc: "Turn CSV data into a PDF table.",
        related: ["pdfToCsv", "excelToPdf", "commaSeparator"]
    },
    pdfUnlock: {
        title: "Unlock PDF",
        desc: "Remove passwords.",
        icon: "fa-solid fa-unlock",
        color: "red",
        category: "pdf_tools",
        mode: "limited",
        badge: "Browser Optimized",
        to: "/unlock-pdf",
        seoTitle: "Unlock PDF",
        seoDesc: "Remove owner passwords from PDFs locally.",
        related: ["pdfMerge", "pdfSplit"]
    },
    pdfRotate: {
        title: "Rotate PDF",
        desc: "Rotate PDF pages.",
        icon: "fa-solid fa-rotate-right",
        color: "orange",
        category: "pdf_tools",
        mode: "enabled",
        badge: "Browser Optimized",
        to: "/rotate-pdf",
        seoTitle: "Rotate PDF Pages Online",
        seoDesc: "Rotate individual PDF pages or the whole document permanently.",
        related: ["pdfSplit", "pdfMerge"]
    },
    pdfSign: {
        title: "Sign PDF",
        desc: "Add signature to PDF.",
        icon: "fa-solid fa-signature",
        color: "blue",
        category: "pdf_actions",
        mode: "enabled",
        to: "/sign-pdf",
        seoTitle: "Sign PDF Online",
        seoDesc: "Draw, type, or upload your signature and add it to any PDF. No signup.",
        related: ["pdfAddText", "pdfAddDate"]
    },
    pdfAddText: {
        title: "Add Text to PDF",
        desc: "Insert text anywhere.",
        icon: "fa-solid fa-font",
        color: "indigo",
        category: "pdf_actions",
        mode: "enabled",
        to: "/add-text-pdf",
        seoTitle: "Add Text to PDF",
        seoDesc: "Insert text, captions, or notes into your PDF document.",
        related: ["pdfSign", "pdfFillForm"]
    },
    pdfFillForm: {
        title: "Fill PDF Form",
        desc: "Type in PDF forms.",
        icon: "fa-solid fa-pen-to-square",
        color: "teal",
        category: "pdf_actions",
        mode: "enabled",
        to: "/fill-pdf-form",
        seoTitle: "Fill PDF Forms Online",
        seoDesc: "Easily fill out non-interactive or scanned PDF forms.",
        related: ["pdfAddText", "pdfSign"]
    },
    pdfAddDate: {
        title: "Add Date to PDF",
        desc: "Insert timestamps.",
        icon: "fa-solid fa-calendar-plus",
        color: "green",
        category: "pdf_actions",
        mode: "enabled",
        to: "/add-date-pdf",
        seoTitle: "Add Date to PDF",
        seoDesc: "Stamp your PDF with current or custom dates.",
        related: ["pdfSign", "pdfAddText"]
    },
    pdfAddImage: {
        title: "Add Image to PDF",
        desc: "Insert logos or photos.",
        icon: "fa-solid fa-image",
        color: "purple",
        category: "pdf_actions",
        mode: "enabled",
        to: "/add-image-pdf",
        seoTitle: "Add Image / Logo to PDF",
        seoDesc: "Insert images, logos, or watermarks into PDF documents.",
        related: ["pdfSign", "jpgToPdf"]
    },
    pdfHighlight: {
        title: "Highlight PDF",
        desc: "Highlight text/areas.",
        icon: "fa-solid fa-highlighter",
        color: "yellow",
        category: "pdf_actions",
        mode: "enabled",
        to: "/highlight-pdf",
        seoTitle: "Highlight Text in PDF",
        seoDesc: "Mark up important text or areas in your PDF.",
        related: ["pdfAddText", "pdfPreview"]
    },

    // CATEGORY 3: ADVANCED
    ocr: {
        title: "OCR",
        desc: "Scan PDF to Text.",
        icon: "fa-solid fa-eye",
        color: "purple",
        category: "advanced_tools",
        mode: "under_development",
        badge: "Coming Soon",
        to: "/ocr",
        seoTitle: "OCR Online",
        seoDesc: "Recognize text in scanned PDFs (Coming Soon).",
        related: ["pdfToText", "pdfToWord", "pdfToJpg"]
    },
    pdfToWord: {
        title: "PDF to Word",
        desc: "Convert to DOCX.",
        icon: "fa-solid fa-file-word",
        color: "blue",
        category: "advanced_tools",
        mode: "under_development",
        badge: "Coming Soon",
        to: "/pdf-to-word",
        seoTitle: "PDF to Word",
        seoDesc: "Convert PDF to Editable Word (Coming Soon).",
        related: ["pdfToText", "pdfToExcel", "wordToPdf"]
    },
    pdfToExcel: {
        title: "PDF to Excel",
        desc: "Convert to Spreadsheet.",
        icon: "fa-solid fa-file-excel",
        color: "emerald",
        category: "advanced_tools",
        mode: "under_development",
        badge: "Coming Soon",
        to: "/pdf-to-excel",
        seoTitle: "PDF to Excel",
        seoDesc: "Extract PDF tables to Excel (Coming Soon).",
        related: ["pdfToCsv", "excelToPdf", "pdfToWord"]
    },
    pdfToCsv: {
        title: "PDF to CSV",
        desc: "Extract tables to CSV.",
        icon: "fa-solid fa-file-csv",
        color: "teal",
        category: "advanced_tools",
        mode: "under_development",
        badge: "Coming Soon",
        to: "/pdf-to-csv",
        seoTitle: "PDF to CSV",
        seoDesc: "Convert tables to CSV format (Coming Soon).",
        related: ["pdfToExcel", "csvToPdf", "commaSeparator"]
    },
    pdfToHtml: {
        title: "PDF to HTML",
        desc: "Convert to HTML.",
        icon: "fa-solid fa-code",
        color: "orange",
        category: "advanced_tools",
        mode: "under_development",
        badge: "Coming Soon",
        to: "/pdf-to-html",
        seoTitle: "PDF to HTML",
        seoDesc: "Convert PDF to HTML (Coming Soon).",
        related: ["pdfToJson", "pdfToText"]
    },
    heavyCompress: {
        title: "Heavy Compression",
        desc: "Max size reduction.",
        icon: "fa-solid fa-file-zipper",
        color: "red",
        category: "advanced_tools",
        mode: "under_development",
        badge: "Coming Soon",
        to: "/heavy-compress",
        seoTitle: "Heavy PDF Compression",
        seoDesc: "Aggressive server-side compression (Coming Soon).",
        related: ["pdfCompress", "pdfToZip"]
    },
    largeFiles: {
        title: "Large File Support",
        desc: "Process files > 50MB.",
        icon: "fa-solid fa-server",
        color: "indigo",
        category: "advanced_tools",
        mode: "under_development",
        badge: "Coming Soon",
        to: "/large-files",
        seoTitle: "Large PDF Processing",
        seoDesc: "Handle large files (Coming Soon).",
        related: ["heavyCompress", "batchProcessing"]
    },
    batchProcessing: {
        title: "Batch Processing",
        desc: "Process multiple files.",
        icon: "fa-solid fa-layer-group",
        color: "cyan",
        category: "advanced_tools",
        mode: "under_development",
        badge: "Coming Soon",
        to: "/batch",
        seoTitle: "Batch PDF Tools",
        seoDesc: "Bulk file processing (Coming Soon).",
        related: ["unlimited", "largeFiles"]
    },
    unlimited: {
        title: "Unlimited Pro",
        desc: "No limits or queues.",
        icon: "fa-solid fa-infinity",
        color: "pink",
        category: "advanced_tools",
        mode: "under_development",
        badge: "Coming Soon",
        to: "/unlimited",
        seoTitle: "Unlimited Tools",
        seoDesc: "Remove all limits (Coming Soon).",
        related: ["batchProcessing", "largeFiles"]
    },
    excelToPdf: {
        title: "Excel to PDF",
        desc: "Convert Excel to PDF.",
        icon: "fa-solid fa-file-excel",
        color: "green",
        category: "advanced_tools",
        mode: "under_development",
        badge: "Coming Soon",
        to: "/excel-to-pdf",
        seoTitle: "Excel to PDF",
        seoDesc: "Convert spreadsheets to PDF (Coming Soon).",
        related: ["pdfToExcel", "csvToPdf", "jsonToPdf"]
    },

    // CATEGORY 4: DEVELOPER TOOLS
    baseConverter: {
        title: "Base Converter",
        desc: "Binary, Decimal, Hex.",
        icon: "fa-solid fa-calculator",
        color: "blue",
        category: "developer_tools",
        mode: "enabled",
        to: "/base-converter",
        seoTitle: "Number Base Converter",
        seoDesc: "Convert between Binary, Octal, Decimal, and Hexadecimal.",
        related: ["timestampConverter", "dataSizeConverter"]
    },
    timestampConverter: {
        title: "Unix Timestamp",
        desc: "Date to Timestamp & back.",
        icon: "fa-solid fa-clock",
        color: "green",
        category: "developer_tools",
        mode: "enabled",
        to: "/timestamp-converter",
        seoTitle: "Unix Timestamp Converter",
        seoDesc: "Convert Unix timestamps to readable dates and vice versa.",
        related: ["dateDiff", "baseConverter"]
    },
    dataSizeConverter: {
        title: "Data Size Converter",
        desc: "Bytes to KB, MB, GB.",
        icon: "fa-solid fa-hard-drive",
        color: "purple",
        category: "developer_tools",
        mode: "enabled",
        to: "/data-size-converter",
        seoTitle: "Data Size Converter",
        seoDesc: "Convert data sizes between Bytes, KB, MB, GB, TB.",
        related: ["baseConverter", "timestampConverter"]
    },
    base64: {
        title: "Base64 tools",
        desc: "Encode & Decode Base64.",
        icon: "fa-solid fa-code",
        color: "orange",
        category: "developer_tools",
        mode: "enabled",
        to: "/base64",
        seoTitle: "Base64 Encoder / Decoder",
        seoDesc: "Encode text to Base64 or decode Base64 to text.",
        related: ["urlEncoder", "htmlEncoder"]
    },
    urlEncoder: {
        title: "URL Encoder",
        desc: "Encode / Decode URLs.",
        icon: "fa-solid fa-link",
        color: "cyan",
        category: "developer_tools",
        mode: "enabled",
        to: "/url-encoder",
        seoTitle: "URL Encoder / Decoder",
        seoDesc: "URL encode or decode strings safely.",
        related: ["base64", "htmlEncoder"]
    },
    htmlEncoder: {
        title: "HTML Encoder",
        desc: "Escape HTML entities.",
        icon: "fa-brands fa-html5",
        color: "red",
        category: "developer_tools",
        mode: "enabled",
        to: "/html-encoder",
        seoTitle: "HTML Encoder / Decoder",
        seoDesc: "Encode or decode HTML entities.",
        related: ["urlEncoder", "base64"]
    },
    uuidGenerator: {
        title: "UUID Generator",
        desc: "Generate UUID v4.",
        icon: "fa-solid fa-fingerprint",
        color: "indigo",
        category: "developer_tools",
        mode: "enabled",
        to: "/uuid-generator",
        seoTitle: "UUID Generator",
        seoDesc: "Generate random UUIDs (Version 4).",
        related: ["randomString", "randomNumber"]
    },
    randomString: {
        title: "Random String",
        desc: "Secure random strings.",
        icon: "fa-solid fa-shuffle",
        color: "pink",
        category: "developer_tools",
        mode: "enabled",
        to: "/random-string",
        seoTitle: "Random String Generator",
        seoDesc: "Generate random passwords and strings.",
        related: ["uuidGenerator", "randomNumber"]
    },
    randomNumber: {
        title: "Random Number",
        desc: "Generate random numbers.",
        icon: "fa-solid fa-dice",
        color: "teal",
        category: "developer_tools",
        mode: "enabled",
        to: "/random-number",
        seoTitle: "Random Number Generator",
        seoDesc: "Generate random numbers within a range.",
        related: ["randomString", "uuidGenerator"]
    },
    scientificCalc: {
        title: "Scientific Calc",
        desc: "Advanced calculations.",
        icon: "fa-solid fa-square-root-variable",
        color: "gray",
        category: "developer_tools",
        mode: "enabled",
        to: "/scientific-calculator",
        seoTitle: "Scientific Calculator",
        seoDesc: "Online scientific calculator for rapid math.",
        related: ["percentageCalc", "dateDiff"]
    },
    percentageCalc: {
        title: "Percentage Calc",
        desc: "Calculate percentages.",
        icon: "fa-solid fa-percent",
        color: "blue",
        category: "developer_tools",
        mode: "enabled",
        to: "/percentage-calculator",
        seoTitle: "Percentage Calculator",
        seoDesc: "Calculate percentages, increases, and decreases.",
        related: ["scientificCalc", "dataSizeConverter"]
    },
    dateDiff: {
        title: "Date Difference",
        desc: "Time between dates.",
        icon: "fa-regular fa-calendar",
        color: "green",
        category: "developer_tools",
        mode: "enabled",
        to: "/date-difference",
        seoTitle: "Date Difference Calculator",
        seoDesc: "Calculate the duration between two dates.",
        related: ["timestampConverter", "scientificCalc"]
    },

    // NETWORK TOOLS
    // NETWORK TOOLS
    ipSubnetCalculator: {
        title: "IP & Subnet Calc",
        desc: "CIDR, Ranges, & Subnets.",
        icon: "fa-solid fa-network-wired",
        color: "blue",
        category: "developer_tools",
        mode: "enabled",
        to: "/ip-subnet-calculator",
        seoTitle: "IP & Subnet Calculator",
        seoDesc: "Calculate subnet details, usable IPs, and IP ranges from a single input.",
        related: ["cidrOverlap", "publicIp", "portLookup"]
    },
    cidrOverlap: {
        title: "CIDR Overlap",
        desc: "Check network overlap.",
        icon: "fa-solid fa-layer-group",
        color: "orange",
        category: "developer_tools",
        mode: "enabled",
        to: "/cidr-overlap",
        seoTitle: "CIDR Overlap Checker",
        seoDesc: "Check if two CIDR network blocks overlap.",
        related: ["ipCalc", "subnetCalc"]
    },

    // LINUX / DEVOPS
    cronGenerator: {
        title: "Cron Generator",
        desc: "Cron schedule builder.",
        icon: "fa-solid fa-clock-rotate-left",
        color: "purple",
        category: "developer_tools",
        mode: "enabled",
        to: "/cron-generator",
        seoTitle: "Crontab Generator",
        seoDesc: "Visual cron job schedule generator for Linux.",
        related: ["chmodCalc", "timestampConverter"]
    },
    chmodCalc: {
        title: "Chmod Calculator",
        desc: "Linux permissions.",
        icon: "fa-solid fa-shield-halved",
        color: "red",
        category: "developer_tools",
        mode: "enabled",
        to: "/chmod-calculator",
        seoTitle: "Chmod Calculator",
        seoDesc: "Calculate numeric (755) and symbolic (rwxr-xr-x) permissions.",
        related: ["cronGenerator", "baseConverter"]
    },

    // NEW DEVELOPER TOOLS (Request 317)
    regexTester: {
        title: "Regex Tester",
        desc: "Test JS regex patterns.",
        icon: "fa-solid fa-vial",
        color: "pink",
        category: "developer_tools",
        mode: "enabled",
        to: "/regex-tester",
        seoTitle: "Regex Tester & debugger",
        seoDesc: "Test and validate JavaScript regular expressions online.",
        related: ["textCleaner", "compareText"]
    },
    caseConverter: {
        title: "Case Converter",
        desc: "Camel, Snake, Kebab case.",
        icon: "fa-solid fa-text-height",
        color: "cyan",
        category: "developer_tools",
        mode: "enabled",
        to: "/case-converter",
        seoTitle: "Case Converter (Camel, Snake, Kebab)",
        seoDesc: "Convert text between camelCase, snake_case, kebab-case, and more.",
        related: ["textCleaner", "slugGenerator"]
    },
    envConverter: {
        title: "Env Var Converter",
        desc: ".env to JSON/YAML.",
        icon: "fa-solid fa-file-code",
        color: "green",
        category: "developer_tools",
        mode: "enabled",
        to: "/env-converter",
        seoTitle: "Environment Variable Converter",
        seoDesc: "Convert .env files to JSON, YAML, or unexpected formats.",
        related: ["jsonFormatter", "yamlConverter"]
    },
    curlConverter: {
        title: "Curl to Code",
        desc: "Curl to Fetch/Axios.",
        icon: "fa-solid fa-terminal",
        color: "blue",
        category: "developer_tools",
        mode: "enabled",
        to: "/curl-converter",
        seoTitle: "Curl to Fetch/Axios Converter",
        seoDesc: "Convert cURL commands to JavaScript Fetch, Axios, or Python Requests.",
        related: ["jsonFormatter", "urlEncoder"]
    },
    diffChecker: {
        title: "Diff Checker",
        desc: "Compare text side-by-side.",
        icon: "fa-solid fa-right-left",
        color: "purple",
        category: "developer_tools",
        mode: "enabled",
        to: "/diff-checker",
        seoTitle: "Online Diff Checker",
        seoDesc: "Compare two text blocks side-by-side and highlight differences.",
        related: ["compareText", "textCleaner"]
    },
    cidrSplitter: {
        title: "CIDR Splitter",
        desc: "Split subnets.",
        icon: "fa-solid fa-scissors",
        color: "orange",
        category: "developer_tools",
        mode: "enabled",
        to: "/cidr-splitter",
        seoTitle: "CIDR Splitter",
        seoDesc: "Split IP CIDR blocks into smaller subnets.",
        related: ["ipCalc", "subnetCalc"]
    },
    k8sConverter: {
        title: "K8s Resources",
        desc: "CPU & Memory units.",
        icon: "fa-solid fa-dharmachakra",
        color: "indigo",
        category: "developer_tools",
        mode: "enabled",
        to: "/k8s-converter",
        seoTitle: "Kubernetes Resource Converter",
        seoDesc: "Convert Kubernetes CPU (millicores) and Memory (Mi/Gi) units.",
        related: ["dataSizeConverter", "yamlConverter"]
    },

    // NEW: MISSING SERVICES (Request 411)
    publicIp: {
        title: "Public IP",
        desc: "Show my IP.",
        icon: "fa-solid fa-globe",
        color: "blue",
        category: "developer_tools",
        mode: "enabled",
        to: "/public-ip",
        seoTitle: "What is my Public IP?",
        seoDesc: "Check your public IPv4/IPv6 address instantly.",
        related: ["ipCalc", "subnetCalc"]
    },
    portLookup: {
        title: "Port Lookup",
        desc: "Check port usage.",
        icon: "fa-solid fa-ethernet",
        color: "teal",
        category: "developer_tools",
        mode: "enabled",
        to: "/port-lookup",
        seoTitle: "Port Number Lookup",
        seoDesc: "Find common services running on specific ports.",
        related: ["ipCalc", "httpStatus"]
    },
    httpStatus: {
        title: "HTTP Status",
        desc: "Status code meaning.",
        icon: "fa-solid fa-server",
        color: "orange",
        category: "developer_tools",
        mode: "enabled",
        to: "/http-status",
        seoTitle: "HTTP Status Code Checker",
        seoDesc: "Understand HTTP status codes (200, 404, 500) and their meanings.",
        related: ["portLookup", "urlEncoder"]
    },
    hashGenerator: {
        title: "Hash Generator",
        desc: "MD5, SHA1, SHA256.",
        icon: "fa-solid fa-fingerprint",
        color: "gray",
        category: "developer_tools",
        mode: "enabled",
        to: "/hash-generator",
        seoTitle: "Online Hash Generator",
        seoDesc: "Generate MD5, SHA-1, and SHA-256 hashes from text using browser crypto.",
        related: ["base64", "uuidGenerator"]
    },
    cronExplainer: {
        title: "Cron Explainer",
        desc: "Explain cron strings.",
        icon: "fa-solid fa-clock",
        color: "purple",
        category: "developer_tools",
        mode: "enabled",
        to: "/cron-explainer",
        seoTitle: "Cron Expression Explainer",
        seoDesc: "Translate cron expressions into human-readable schedules.",
        related: ["cronGenerator", "timestampConverter"]
    },
    timezoneConverter: {
        title: "Timezone Converter",
        desc: "Convert world time.",
        icon: "fa-solid fa-earth-americas",
        color: "indigo",
        category: "developer_tools",
        mode: "enabled",
        to: "/timezone-converter",
        seoTitle: "Timezone Converter",
        seoDesc: "Convert time between UTC, Local, and other timezones.",
        related: ["timestampConverter", "dateDiff"]
    },

    // CATEGORY 5: EXCEL & DATA TOOLS
    excelToJson: {
        title: "Excel/CSV to JSON",
        desc: "Convert to JSON.",
        icon: "fa-solid fa-file-csv",
        color: "green",
        category: "excel_tools",
        mode: "enabled",
        to: "/excel-to-json",
        seoTitle: "Excel & CSV to JSON Converter",
        seoDesc: "Convert Excel (XLSX) or CSV files to JSON format online.",
        related: ["jsonToExcel", "csvCleaner", "jsonFormatter"]
    },
    jsonToExcel: {
        title: "JSON to Excel/CSV",
        desc: "Convert to Table.",
        icon: "fa-solid fa-table",
        color: "blue",
        category: "excel_tools",
        mode: "enabled",
        to: "/json-to-excel",
        seoTitle: "JSON to Excel & CSV Converter",
        seoDesc: "Convert JSON data to Excel (XLSX) or CSV files instantly.",
        related: ["excelToJson", "csvCleaner", "jsonValidator"]
    },
    csvCleaner: {
        title: "CSV Cleaner",
        desc: "Clean & Format CSV.",
        icon: "fa-solid fa-broom",
        color: "orange",
        category: "excel_tools",
        mode: "enabled",
        to: "/csv-cleaner",
        seoTitle: "Online CSV Cleaner & Formatter",
        seoDesc: "Remove empty rows, trim whitespace, and normalize CSV headers.",
        related: ["excelToJson", "jsonToExcel", "textCleaner"]
    },
    formulaExplainer: {
        title: "Formula Explainer",
        desc: "Explain Excel Formulas.",
        icon: "fa-solid fa-wand-magic-sparkles",
        color: "purple",
        category: "excel_tools",
        mode: "enabled",
        to: "/formula-explainer",
        seoTitle: "Excel Formula Explainer",
        seoDesc: "Understand complex Excel formulas in plain English.",
        related: ["excelToJson", "scientificCalc"]
    },

    // EXCEL: CONVERSIONS
    excelToCsv: {
        title: "Excel to CSV",
        desc: "Convert XLSX to CSV.",
        icon: "fa-solid fa-file-csv",
        color: "green",
        category: "excel_tools",
        mode: "enabled",
        to: "/excel-to-csv",
        seoTitle: "Excel to CSV Converter",
        seoDesc: "Convert Excel sheets to CSV files instantly.",
        related: ["csvToExcel", "excelToJson"]
    },
    csvToExcel: {
        title: "CSV to Excel",
        desc: "Convert CSV to XLSX.",
        icon: "fa-solid fa-file-excel",
        color: "blue",
        category: "excel_tools",
        mode: "enabled",
        to: "/csv-to-excel",
        seoTitle: "CSV to Excel Converter",
        seoDesc: "Convert CSV files to Excel spreadsheets.",
        related: ["excelToCsv", "jsonToExcel"]
    },
    excelToSql: {
        title: "Excel to SQL",
        desc: "Generate INSERT statements.",
        icon: "fa-solid fa-database",
        color: "orange",
        category: "excel_tools",
        mode: "enabled",
        to: "/excel-to-sql",
        seoTitle: "Excel to SQL Converter",
        seoDesc: "Convert Excel rows into SQL INSERT statements.",
        related: ["excelToJson", "excelToCsv"]
    },
    excelToYaml: {
        title: "Excel to YAML",
        desc: "Convert rows to YAML.",
        icon: "fa-solid fa-code",
        color: "teal",
        category: "excel_tools",
        mode: "enabled",
        to: "/excel-to-yaml",
        seoTitle: "Excel to YAML Converter",
        seoDesc: "Convert Excel data to YAML format.",
        related: ["excelToJson", "jsonFormatter"]
    },

    // EXCEL: DATA CLEANING & OPS
    duplicateFinder: {
        title: "Duplicate Finder",
        desc: "Find & Remove Duplicates.",
        icon: "fa-solid fa-clone",
        color: "red",
        category: "excel_tools",
        mode: "enabled",
        to: "/duplicate-finder",
        seoTitle: "Excel Duplicate Finder",
        seoDesc: "Find and remove duplicate rows in Excel/CSV.",
        related: ["csvCleaner", "compareText"]
    },
    columnSplitter: {
        title: "Column Splitter",
        desc: "Split text to columns.",
        icon: "fa-solid fa-table-columns",
        color: "indigo",
        category: "excel_tools",
        mode: "enabled",
        to: "/column-splitter",
        seoTitle: "Excel Column Splitter",
        seoDesc: "Split one column into multiple based on a delimiter.",
        related: ["excelToCsv", "textCleaner"]
    },
    transpose: {
        title: "Transpose",
        desc: "Switch Rows & Columns.",
        icon: "fa-solid fa-rotate-90",
        color: "pink",
        category: "excel_tools",
        mode: "enabled",
        to: "/transpose-excel",
        seoTitle: "Excel Transpose Tool",
        seoDesc: "Rotate Excel data: switch rows to columns.",
        related: ["excelToCsv", "jsonToExcel"]
    },

    // EXCEL: UTILS
    excelDate: {
        title: "Excel Date Converter",
        desc: "Serial to Date.",
        icon: "fa-solid fa-calendar-check",
        color: "blue",
        category: "excel_tools",
        mode: "enabled",
        to: "/excel-date-converter",
        seoTitle: "Excel Date Serial Converter",
        seoDesc: "Convert Excel serial date numbers to human readable dates.",
        related: ["dateDiff", "timestampConverter"]
    },
    formulaGenerator: {
        title: "Formula Generator",
        desc: "Create simple formulas.",
        icon: "fa-solid fa-calculator",
        color: "purple",
        category: "excel_tools",
        mode: "enabled",
        to: "/formula-generator",
        seoTitle: "Excel Formula Generator",
        seoDesc: "Generate Excel formulas for common tasks.",
        related: ["formulaExplainer", "scientificCalc"]
    },
    excelErrorExplainer: {
        title: "Error Explainer",
        desc: "Explain #N/A, #VALUE!",
        icon: "fa-solid fa-bug",
        color: "red",
        category: "excel_tools",
        mode: "enabled",
        to: "/excel-error-explainer",
        seoTitle: "Excel Error Explainer",
        seoDesc: "Understand #VALUE!, #N/A, #REF! and other Excel errors.",
        related: ["formulaExplainer", "formulaGenerator"]
    },
    columnMerger: {
        title: "Column Merger",
        desc: "Combine columns.",
        icon: "fa-solid fa-object-group",
        color: "indigo",
        category: "excel_tools",
        mode: "enabled",
        to: "/column-merger",
        seoTitle: "Merge Excel Columns",
        seoDesc: "Combine two columns into one with a delimiter.",
        related: ["columnSplitter", "excelToCsv"]
    },
    headerNormalizer: {
        title: "Header Normalizer",
        desc: "Fix Table Headers.",
        icon: "fa-solid fa-text-height",
        color: "teal",
        category: "excel_tools",
        mode: "enabled",
        to: "/header-normalizer",
        seoTitle: "Excel Header Normalizer",
        seoDesc: "Convert headers to snake_case, camelCase, or clean format.",
        related: ["csvCleaner", "jsonToExcel"]
    },
    excelDataProcessor: {
        title: "Excel Data Processor",
        desc: "Filter, Dedup, & Clean.",
        icon: "fa-solid fa-filter-circle-xmark",
        color: "blue",
        category: "excel_tools",
        mode: "enabled",
        to: "/excel-data-processor",
        seoTitle: "Excel Data Processor",
        seoDesc: "Filter, clean, and remove duplicates from Excel or CSV files online. Free, fast, and no signup.",
        related: ["csvCleaner", "excelToJson"]
    },
    jwtDecoder: {
        title: "JWT Decoder",
        desc: "Decode & Verify Tokens.",
        icon: "fa-solid fa-shield-halved",
        color: "red",
        category: "developer_tools",
        mode: "enabled",
        to: "/jwt-decoder",
        seoTitle: "JWT Decoder & Validator",
        seoDesc: "Decode, verify, and inspect JWT tokens securely in your browser.",
        related: ["base64", "timestampConverter"]
    },
    sshGenerator: {
        title: "SSH Key Gen",
        desc: "Generate RSA Key Pairs.",
        icon: "fa-solid fa-key",
        color: "green",
        category: "developer_tools",
        mode: "enabled",
        to: "/ssh-generator",
        seoTitle: "Online SSH Key Generator",
        seoDesc: "Generate RSA SSH keys with passphrases in your browser.",
        related: ["uuidGenerator", "jwtDecoder"]
    }

};

export const FEATURE_CONFIG = {
    features: FEATURES,
    categories: FEATURE_CATEGORIES
};
