import React, { useState } from 'react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { Download, Loader2 } from 'lucide-react';

export const DownloadReport = ({ title, contentRef }) => {
    const [loading, setLoading] = useState(false);

    const handleDownload = async () => {
        if (!contentRef.current) return;
        setLoading(true);

        try {
            const element = contentRef.current;
            const canvas = await html2canvas(element, {
                scale: 2, // Higher quality
                backgroundColor: '#ffffff', // Ensure white background for PDF
                logging: false,
                useCORS: true
            });

            const imgData = canvas.toDataURL('image/png');
            const pdf = new jsPDF({
                orientation: 'portrait',
                unit: 'mm',
                format: 'a4'
            });

            const pdfWidth = pdf.internal.pageSize.getWidth();
            const pdfHeight = pdf.internal.pageSize.getHeight();
            const imgWidth = pdfWidth;
            const imgHeight = (canvas.height * imgWidth) / canvas.width;

            // Header - Branding
            pdf.setFontSize(16);
            pdf.setTextColor(40, 40, 40);
            pdf.text("Finance Planner Report", 10, 10);
            pdf.setFontSize(10);
            pdf.setTextColor(100, 100, 100);
            pdf.text(`Generated on ${new Date().toLocaleDateString()}`, 10, 16);

            // Warning if content is too long (simplified single page for now)
            let heightLeft = imgHeight;
            let position = 20; // Start below header

            pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);

            // Footer - Footprints
            pdf.setFontSize(8);
            pdf.setTextColor(150, 150, 150);
            const footerText = "Generated by IntelliFlow Suite | Your Financial Partner";
            pdf.text(footerText, pdfWidth / 2, pdfHeight - 10, { align: 'center' });

            pdf.save(`${title.replace(/\s+/g, '_').toLowerCase()}_report.pdf`);
        } catch (error) {
            console.error("PDF Generation Failed", error);
            alert("Could not generate PDF. Please try again.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <button
            onClick={handleDownload}
            disabled={loading}
            className="flex items-center gap-2 px-4 py-2 bg-gray-900 dark:bg-white text-white dark:text-gray-900 rounded-lg text-sm font-bold hover:opacity-90 transition-opacity disabled:opacity-50"
        >
            {loading ? <Loader2 size={16} className="animate-spin" /> : <Download size={16} />}
            {loading ? "Generating..." : "Download Report"}
        </button>
    );
};
